-- ============================================================
-- RePlate
-- Smart Surplus Food Recovery & Redistribution Platform
-- Database Schema
-- PostgreSQL / Supabase
-- ============================================================


-- ============================================================
-- 1. EXTENSIONS
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 2. PROFILES
-- Links application users to Supabase Auth users
-- ============================================================

CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,

    full_name TEXT NOT NULL,

    phone TEXT,

    email TEXT,

    address TEXT,

    city TEXT,

    state TEXT,

    pincode TEXT,

    avatar_url TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 3. ROLES
-- ============================================================

CREATE TABLE public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL UNIQUE,

    description TEXT
);


-- ============================================================
-- 4. USER ROLES
-- Many-to-many relationship between users and roles
-- ============================================================

CREATE TABLE public.user_roles (
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,

    role_id BIGINT NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,

    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, role_id)
);


-- ============================================================
-- 5. PROVIDER PROFILES
-- Restaurants, hotels, bakeries, caterers, supermarkets, etc.
-- ============================================================

CREATE TABLE public.provider_profiles (
    id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,

    organization_name TEXT NOT NULL,

    provider_type TEXT NOT NULL,

    description TEXT,

    registration_number TEXT,

    operating_hours TEXT,

    pickup_address TEXT,

    latitude NUMERIC(9,6),

    longitude NUMERIC(9,6),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 6. NGO PROFILES
-- ============================================================

CREATE TABLE public.ngo_profiles (
    id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,

    organization_name TEXT NOT NULL,

    registration_number TEXT,

    description TEXT,

    service_area TEXT,

    beneficiary_count INTEGER DEFAULT 0,

    storage_capacity_kg NUMERIC(10,2) DEFAULT 0,

    pickup_capability BOOLEAN NOT NULL DEFAULT FALSE,

    address TEXT,

    latitude NUMERIC(9,6),

    longitude NUMERIC(9,6),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT ngo_beneficiary_count_check
        CHECK (beneficiary_count >= 0),

    CONSTRAINT ngo_storage_capacity_check
        CHECK (storage_capacity_kg >= 0)
);


-- ============================================================
-- 7. VOLUNTEER PROFILES
-- ============================================================

CREATE TABLE public.volunteer_profiles (
    id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,

    vehicle_type TEXT,

    availability_status TEXT NOT NULL DEFAULT 'available',

    service_area TEXT,

    latitude NUMERIC(9,6),

    longitude NUMERIC(9,6),

    completed_deliveries INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT volunteer_status_check
        CHECK (
            availability_status IN (
                'available',
                'busy',
                'offline'
            )
        ),

    CONSTRAINT volunteer_deliveries_check
        CHECK (completed_deliveries >= 0)
);


-- ============================================================
-- 8. FOOD CATEGORIES
-- ============================================================

CREATE TABLE public.food_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL UNIQUE,

    description TEXT
);


-- ============================================================
-- 9. FOOD LISTINGS
-- Food donated by providers
-- ============================================================

CREATE TABLE public.food_listings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    provider_id UUID NOT NULL
        REFERENCES public.provider_profiles(id)
        ON DELETE CASCADE,

    category_id BIGINT NOT NULL
        REFERENCES public.food_categories(id),

    title TEXT NOT NULL,

    description TEXT,

    quantity NUMERIC(10,2) NOT NULL,

    quantity_unit TEXT NOT NULL DEFAULT 'kg',

    prepared_at TIMESTAMPTZ,

    expiry_time TIMESTAMPTZ NOT NULL,

    pickup_start_time TIMESTAMPTZ,

    pickup_end_time TIMESTAMPTZ,

    pickup_address TEXT,

    latitude NUMERIC(9,6),

    longitude NUMERIC(9,6),

    status TEXT NOT NULL DEFAULT 'draft',

    image_url TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT food_quantity_check
        CHECK (quantity > 0),

    CONSTRAINT food_status_check
        CHECK (
            status IN (
                'draft',
                'available',
                'reserved',
                'picked_up',
                'delivered',
                'completed',
                'expired',
                'cancelled'
            )
        ),

    CONSTRAINT pickup_time_check
        CHECK (
            pickup_end_time IS NULL
            OR pickup_start_time IS NULL
            OR pickup_end_time >= pickup_start_time
        )
);


-- ============================================================
-- 10. FOOD REQUESTS
-- NGOs request available food
-- ============================================================

CREATE TABLE public.food_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    listing_id UUID NOT NULL
        REFERENCES public.food_listings(id)
        ON DELETE CASCADE,

    ngo_id UUID NOT NULL
        REFERENCES public.ngo_profiles(id)
        ON DELETE CASCADE,

    requested_quantity NUMERIC(10,2) NOT NULL,

    message TEXT,

    status TEXT NOT NULL DEFAULT 'pending',

    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    responded_at TIMESTAMPTZ,

    CONSTRAINT requested_quantity_check
        CHECK (requested_quantity > 0),

    CONSTRAINT request_status_check
        CHECK (
            status IN (
                'pending',
                'approved',
                'rejected',
                'cancelled'
            )
        )
);


-- ============================================================
-- 11. DELIVERIES
-- One delivery belongs to one approved food request
-- ============================================================

CREATE TABLE public.deliveries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    request_id UUID NOT NULL UNIQUE
        REFERENCES public.food_requests(id)
        ON DELETE CASCADE,

    volunteer_id UUID
        REFERENCES public.volunteer_profiles(id)
        ON DELETE SET NULL,

    status TEXT NOT NULL DEFAULT 'pending_assignment',

    assigned_at TIMESTAMPTZ,

    pickup_time TIMESTAMPTZ,

    delivery_time TIMESTAMPTZ,

    notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT delivery_status_check
        CHECK (
            status IN (
                'pending_assignment',
                'assigned',
                'picked_up',
                'in_transit',
                'delivered',
                'cancelled'
            )
        )
);


-- ============================================================
-- 12. IMPACT RECORDS
-- Stores environmental/social impact
-- ============================================================

CREATE TABLE public.impact_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    listing_id UUID NOT NULL UNIQUE
        REFERENCES public.food_listings(id)
        ON DELETE CASCADE,

    food_saved_kg NUMERIC(10,2) NOT NULL DEFAULT 0,

    meals_served INTEGER NOT NULL DEFAULT 0,

    beneficiaries_count INTEGER NOT NULL DEFAULT 0,

    co2_saved_kg NUMERIC(10,2) NOT NULL DEFAULT 0,

    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT food_saved_check
        CHECK (food_saved_kg >= 0),

    CONSTRAINT meals_served_check
        CHECK (meals_served >= 0),

    CONSTRAINT beneficiaries_check
        CHECK (beneficiaries_count >= 0),

    CONSTRAINT co2_saved_check
        CHECK (co2_saved_kg >= 0)
);


-- ============================================================
-- 13. NOTIFICATIONS
-- ============================================================

CREATE TABLE public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,

    title TEXT NOT NULL,

    message TEXT NOT NULL,

    notification_type TEXT,

    related_listing_id UUID
        REFERENCES public.food_listings(id)
        ON DELETE CASCADE,

    related_request_id UUID
        REFERENCES public.food_requests(id)
        ON DELETE CASCADE,

    is_read BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 14. INSERT DEFAULT ROLES
-- ============================================================

INSERT INTO public.roles (name, description)
VALUES
    ('provider', 'Restaurant, hotel, bakery, caterer or other food provider'),
    ('ngo', 'NGO or organization receiving surplus food'),
    ('volunteer', 'Volunteer responsible for pickup and delivery'),
    ('admin', 'System administrator')
ON CONFLICT (name) DO NOTHING;


-- ============================================================
-- 15. INSERT DEFAULT FOOD CATEGORIES
-- ============================================================

INSERT INTO public.food_categories (name, description)
VALUES
    ('Cooked Meals', 'Prepared and ready-to-eat meals'),
    ('Bakery Items', 'Bread, cakes, pastries and similar products'),
    ('Fruits & Vegetables', 'Fresh fruits and vegetables'),
    ('Packaged Food', 'Packaged or sealed food products'),
    ('Beverages', 'Drinks and other beverages'),
    ('Other', 'Other types of surplus food')
ON CONFLICT (name) DO NOTHING;


-- ============================================================
-- 16. UPDATED_AT TRIGGER FUNCTION
-- Automatically updates updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


-- ============================================================
-- 17. UPDATED_AT TRIGGERS
-- ============================================================

CREATE TRIGGER update_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();


CREATE TRIGGER update_provider_profiles_updated_at
BEFORE UPDATE ON public.provider_profiles
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();


CREATE TRIGGER update_ngo_profiles_updated_at
BEFORE UPDATE ON public.ngo_profiles
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();


CREATE TRIGGER update_volunteer_profiles_updated_at
BEFORE UPDATE ON public.volunteer_profiles
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();


CREATE TRIGGER update_food_listings_updated_at
BEFORE UPDATE ON public.food_listings
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();


CREATE TRIGGER update_deliveries_updated_at
BEFORE UPDATE ON public.deliveries
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();


-- ============================================================
-- 18. INDEXES
-- ============================================================

CREATE INDEX idx_user_roles_user_id
ON public.user_roles(user_id);


CREATE INDEX idx_user_roles_role_id
ON public.user_roles(role_id);


CREATE INDEX idx_food_listings_provider
ON public.food_listings(provider_id);


CREATE INDEX idx_food_listings_category
ON public.food_listings(category_id);


CREATE INDEX idx_food_listings_status
ON public.food_listings(status);


CREATE INDEX idx_food_listings_expiry
ON public.food_listings(expiry_time);


CREATE INDEX idx_food_requests_listing
ON public.food_requests(listing_id);


CREATE INDEX idx_food_requests_ngo
ON public.food_requests(ngo_id);


CREATE INDEX idx_food_requests_status
ON public.food_requests(status);


CREATE INDEX idx_deliveries_volunteer
ON public.deliveries(volunteer_id);


CREATE INDEX idx_deliveries_status
ON public.deliveries(status);


CREATE INDEX idx_notifications_user
ON public.notifications(user_id);


CREATE INDEX idx_notifications_read
ON public.notifications(is_read);


-- ============================================================
-- END OF RePlate SCHEMA
-- ============================================================

-- ============================================================
-- POLICY MAKING
CREATE POLICY "Anyone can view food categories"
ON public.food_categories
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Users can view their own profile"
ON public.profiles
FOR SELECT
TO authenticated
USING (auth.uid() = id);


CREATE POLICY "Users can update their own profile"
ON public.profiles
FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);
-- =============================================================
